{
    'name': 'Asiup Shopbase Integration',
    'summary': 'Asiup Shopbase Integration',
    'description': 'Asiup Shopbase Integration',
    'category': 'Integration',
    'version': '14.0.1.0.0',
    'depends': ['asiup_email', 'asiup_product', 'queue_job', 'common_connector_library', 'delivery', 'asiup_paypal_integration',
                'web_widget_url_advanced', 'sh_message_wizard','sms_notification'],
    'external_dependencies': {
        'python': ['zipcodes']
    },
    'data': [
        'data/new_tracking_number.xml',
        'data/cancel_order.xml',
        'data/change_tracking.xml',
        'data/order_change.xml',
        'data/order_create.xml',
        'data/order_line_success.xml',
        'data/refund_partially.xml',
        'data/refundsuccess.xml',
        'data/cron_data.xml',
        'data/delivery_status_general.xml',
        'security/ir.model.access.csv',
        'security/asiup_security.xml',
        'views/shopbase_menu.xml',
        'views/store_shopbase_view.xml',
        'views/product_store_view.xml',
        'views/shopbase_webhook_view.xml',
        'views/res_config_setting.xml',
        'views/res_partner_view.xml',
        'views/sale_order_view.xml',
        'views/refund_request_view.xml',
        'views/request_pending_view.xml',
        'views/request_cancel_view.xml',
        'views/product_variant_image_shopbase.xml',
        'views/payment_gateway_view.xml',
        'views/tracking_courier_view.xml',
        'views/templates.xml',
        'views/request_reship_view.xml',
        'wizard/update_product_price.xml',
        'views/sale_order_email_action.xml',
        'wizard/order_message.xml'
    ],
    'application': True,
}
